routes/web.php
<?php

use App\Http\Controllers\Blog\PostsController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'WelcomeController@index');
Route::get('/blog/posts/{post}', [PostsController::class, 'show'])->name('blog.show');

Auth::routes();


Route::middleware(['auth'])->group(function () {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('categories', 'CategoriesController');
    Route::resource('posts', 'PostsController');
    Route::get('trashed-posts', 'PostsController@trashed')->name('trashed-posts.index');
    Route::put('restore-post/{post}', 'PostsController@restore')->name('restore-post');
    Route::resource('tags', 'TagsController');
    
});
Route::middleware(['auth', 'admin'])->group(function(){
    Route::get('users/profile', 'UsersController@edit')->name('users.edit-profile');
    Route::put('users/profile', 'UsersController@update')->name('users.update-profie');
    Route::get('users', 'UsersController@index')->name('users.index');
    Route::post('users/{user}/make-admin', 'UsersController@makeAdmin')->name('users.make-admin');
});

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Storage;

class Post extends Model
{
    use SoftDeletes;
    protected $fillable = ['title', 'description', 'content', 'image', 'user_id', 'published_at', 'category_id'];

    
    public function deleteImage()
    {
        Storage::delete($this->image);
    }
    public function category()
    {
        return $this->belongsTo(Category::class);
    }
    public function tags()
    {
        return $this->belongsToMany(Tag::class);
    }

    public function hasTag($tagId)
    {
        return in_array($tagId, $this->tags->pluck('id')->toArray());
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/Blog/PostsController.php
<?php

namespace App\Http\Controllers\Blog;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Post;

class PostsController extends Controller
{
    public function show(Post $post)
    {
        return view('blog.show')->with('post', $post);
    }
}

app/Http/Controllers/PostsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\Posts\CreatePostRequest;
use App\Http\Requests\Posts\UpdatePostRequest;

use App\Post;
use App\Category;
use App\Tag;

class PostsController extends Controller
{
    public function __construct()
    {
        $this->middleware('verifyCategoriesCount')->only(['create', 'store']);
        
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('posts.index')->with('posts', Post::all());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        return view('posts.create')->with('categories', Category::all())->with('tags', Tag::all());
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreatePostRequest $request)
    {
        //upload a image
        
        $image = $request->image->store('posts');
        $post = Post::create([
            'title' => $request->title,
            'description' => $request->description,
            'content' => $request->content,
            'published_at' => $request->published_at,
            'image' => $image,
            'category_id' => $request->category,
            'user_id' => auth()->user()->id
        ]);
        if ($request->tags) {
            $post->tags()->attach($request->tags);
        }
        session()->flash('success', 'Post Created Successfully');
        return redirect(route('posts.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $post)
    {
        return view('posts.create')->with('post', $post)->with('categories', Category::all())->with('tags', Tag::all());
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdatePostRequest $request, Post $post)
    {
        $data = $request->only(['title', 'description', 'published_at', 'content', 'category_id']);
        if($request->hasFile('image')){
            $image = $request->image->store('posts');
            $post->deleteImage();
            $data['image'] = $image;
            
        }
        if ($request->tags) {
            $post->tags()->sync($request->tags);
        }

        $post->update($data);

        session()->flash('success', 'Post Updated Successfully');
        return redirect(route('posts.index'));
        

    }


    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $post = Post::withTrashed()->where('id', $id)->firstOrFail();
        if($post->trashed()){
            $post->deleteImage();
            $post->forceDelete();
        } else{
            $post->delete();
        }
        session()->flash('success', 'Post Deleted Successfully');
        return redirect(route('posts.index'));
        
    }
    public function trashed()
    {
        $trashed = Post::onlyTrashed()->get();

        return view('posts.index')->withPosts($trashed);
    }

    public function restore($id)
    {
        $post = Post::withTrashed()->where('id', $id)->firstOrFail();
        $post->restore();

        session()->flash('success', 'Post Restored Successfully');
        return redirect()->back();

    }
}

resources/views/posts/create.blade.php
@extends('layouts.app')


@section('content')

<div class="card car-default">
  <div class="card-header">
    {{ isset($post) ? 'Edit Post': 'Create Post'}}
  </div>
  <div class="card-body">
    @include('partials.errors')
  <form action="{{ isset($post) ? route('posts.update', $post->id) : route('posts.store') }}" method="POST" enctype="multipart/form-data">
  @csrf
  @if (isset($post))
    @method('PUT')      
  @endif
  <div class="form-group">
      <label for="title">Title</label>
  <input type="text" id = "title" class="form-control" name="title" value="{{ isset($post) ? $post->title: ''}}">
    </div>
  <div class="form-group">
      <label for="description">Description</label>
  <input type="text" id = "description" class="form-control" name="description" value="{{ isset($post) ? $post->description: ''}}">

  </div>
  <div class="form-group">
      <label for="content">Content</label>
  <input id="content" type="hidden" name="content" value="{{ isset($post) ? $post->content: ''}}">
    <trix-editor input="content"></trix-editor>

  </div>

  <div class="form-group">
      <label for="published_at">Published At</label>
    <input type="text" id = "published_at" class="form-control" name="published_at" value="{{ isset($post) ? $post->published_at: ''}}" >
    </div>

    @if (isset($post))
      <div class="form-group">
      <img src="{{ asset("/storage/".$post->image )}}"style="width:100%" alt="">
      </div>
        
    @endif
       
    <div class="form-group">
        <label for="image">Image</label>
      <input type="file" id = "image" class="form-control" name="image" >
      </div>
      <div class="form-group">
        <label for="category">Category</label>
        <select name="category" id="category" class="form-control">
          @foreach ($categories as $category)
        <option value="{{ $category->id }}"
          @if (isset($post))
            @if ($category->id === $post->category_id)
                selected              
            @endif
          @endif
          >

        {{ $category->name }}
        </option> 
          @endforeach
        </select>
    
      </div>
      @if ($tags->count() > 0)
      <div class="form-group">
        <label for="tags">Tags</label>
        
          <select name="tags[]" id="tags" class="form-control tags-selector" multiple>
            @foreach ($tags as $tag)
              <option value="{{ $tag->id }}"
               @if (isset($post))
                    @if ($post->hasTag($tag->id))

                    selected 
                      
                  @endif
                   
               @endif
                >
                {{ $tag->name }}
              </option>
                
            @endforeach
          </select>
              
       
      </div>
    
      @endif
      
    <div class="form-group">
    <button type="submit" class="btn btn-success">
    {{ isset($post) ? 'Update Post': 'Create Post'}}  
    </button>  
    </div>  
       
  </form>
    
  </div>
</div>
    
@endsection
@section('scripts')
  
  <script src="https://cdnjs.cloudflare.com/ajax/libs/trix/1.2.1/trix.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
  <script src="https://cdn.jsdelivr.net/npm/select2@4.0.12/dist/js/select2.min.js"></script>
 <script>
   flatpickr('#published_at', {
     enableTime: true 
   })

   $(document).ready(function() {
    $('.tags-selector').select2();
});
 </script>
 
@endsection

@section('css')
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/trix/1.2.1/trix.css">    
  <link href="https://cdn.jsdelivr.net/npm/select2@4.0.12/dist/css/select2.min.css" rel="stylesheet" />

  @endsection

resources/views/posts/index.blade.php
@extends('layouts.app')

@section('content')
<div class="d-flex justify-content-end mb-2">
<a href="{{route('posts.create')}}" class="btn btn-success">Add Post</a>
</div>
<div class="card car-default">
  <div class="card-header">
    Posts
  </div>
  <div class="card-body">
  @if ($posts->count() > 0)

  <table class="table">
    <thead>
      <th>Image</th>
      <th>Title</th>
      <th>Category</th>
      <th></th>
      <th></th>
    </thead>
    <tbody>
      @foreach ($posts as $post)
        <tr>
        <td>
          <img src= "{{ asset("/storage/".$post->image) }}" width="120px" height="60px" alt="">
        </td>
          <td>
            {{ $post->title }}
          </td>
          <td>
          <a href="{{ route('categories.edit', $post->category->id) }}">
            {{ $post->category->name }}
          </a>  
          </td>

         @if ($post->trashed())
          <td>
          <form action="{{ route('restore-post', $post->id)}}" method="POST">
              @csrf
              @method('PUT')
              <button type ="submit" class="btn btn-info btn-sm">Restore</button>
            </form>
          
          </td>
          @else
          <td>
            <a href="{{ route('posts.edit', $post->id)}}" class="btn btn-info btn-sm">Edit</a>
            </td>

         @endif
          <td>
          <form action="{{ route('posts.destroy', $post->id)}}" method="POST">
            @csrf
            @method('DELETE')

            <button type="submit" class="btn btn-danger btn-sm">
              {{ $post->trashed() ? 'Delete' : 'Trash' }}
            </button>
            </form>
          </td>

          
        </tr>
          
      @endforeach
    </tbody>
  </table>

  @else
  <h3 class="text-center">
    No Post Yet
  </h3>
      
  @endif  
  </div>
</div>
    
@endsection